services:
  - type: web
    name: llama3-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard  # ou starter
    region: oregon
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
    healthCheckPath: /
    autoDeploy: true